name-template: 'Patch Release {version}'
tag-template: '_DRAFT_'
template: |
  ## What’s Changed in this release

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: Hotfixes 🔥
    labels: ["hotfix"]