name-template: 'Release {version}'
tag-template: '_DRAFT_'
template: |
  ## What’s Changed in this release

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: New Features & Enhancements 🎉
    labels: ["feature"]
  - title: Bug Fixes & Issue Resolutions 🐛
    labels: ["fix"]
  - title: Defect Fixes 🔧
    labels: ["defect"]
  - title: Chores & Maintenance 🧹
    labels: ["chore"]
  - title: Performance Improvements ⚡
    labels: ["performance"]
  - title: Code Refactoring 🔄
    labels: ["refactor"]
  - title: Security Enhancements 🔒
    labels: ["security"]
  - title: Documentation Updates 📚
    labels: ["docs"]
  - title: Test Improvements 🧪
    labels: ["test"]
  - title: Reverted Changes ↩️
    labels: ["revert"]