name: Automate hotfix Pr's on PR to main.

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'hotfix/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create PR from hotfix branch to develop
        run: |
          gh pr create \
            --base develop \
            --head ${{ github.head_ref }} \
            --title "Hotfix: Merge ${{ github.head_ref }} into develop" \
            --body "This PR applies the hotfix changes from ${{ github.head_ref }} to develop."
            --label "automated" \
            --label "hotfix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

