name: Release Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Step 2: Fetch the latest tag
    - name: Fetch the latest tag
      run: |
        latest_tag=$(gh release list --limit 1 --json tagName -q '.[0].tagName')

        # Fetch the release notes
        release_notes=$(gh release view $latest_tag --json body --jq '.body')

        # Create a 'docs' folder if it doesn't exist
        mkdir -p docs

        # Save the release notes with the version number in the file name
        echo "${release_notes}" > "docs/Release v${latest_tag}.md"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Load config from JSON and set environment variables
    - name: Load config from JSON
      id: load_config
      run: |
        # Extract and export the required Confluence settings directly
        confluenceBaseUrl=$(jq -r '.confluenceSettings.confluenceBaseUrl' workflow.config.json)
        confluenceParentId=$(jq -r '.confluenceSettings.confluenceParentId' workflow.config.json)
        atlassianUserName=$(jq -r '.confluenceSettings.atlassianUserName' workflow.config.json)
        folderToPublish=$(jq -r '.confluenceSettings.folderToPublish' workflow.config.json)
        
        # Debugging: Print extracted values
        echo "Confluence Base URL: $confluenceBaseUrl"
        echo "Confluence Parent ID: $confluenceParentId"
        echo "Atlassian Username: $atlassianUserName"
        echo "Folder to Publish: $folderToPublish"

        # Export the values to the environment for the next steps
        echo "confluenceBaseUrl=$confluenceBaseUrl" >> $GITHUB_ENV
        echo "confluenceParentId=$confluenceParentId" >> $GITHUB_ENV
        echo "atlassianUserName=$atlassianUserName" >> $GITHUB_ENV
        echo "folderToPublish=$folderToPublish" >> $GITHUB_ENV

    # Step 4: Publish Markdown to Confluence
    - name: Publish Markdown to Confluence
      uses: markdown-confluence/publish-action@v5
      with:
        confluenceBaseUrl: ${{ env.confluenceBaseUrl }}
        confluenceParentId: ${{ env.confluenceParentId }}
        atlassianUserName: ${{ env.atlassianUserName }}
        atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
        folderToPublish: ${{ env.folderToPublish }}
