name: Create Confluence Release Notes
on:
  workflow_run:
    workflows: ["Create Release"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Fetch release notes
      - name: Fetch release notes
        id: fetch_release_notes
        run: |
          # Fetch the latest tag
          latest_tag=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          
          # Fetch the release notes
          release_notes=$(gh release view $latest_tag --json body --jq '.body')

          # Create a 'docs' folder if it doesn't exist
          mkdir -p docs
          
          # Save the release notes with the version number in the file name
          echo "${release_notes}" > "docs/release_notes_${latest_tag}.md"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Verify docs folder and permissions
      - name: Verify docs folder and permissions
        run: |
          echo "Verifying contents of the workspace..."
          ls -la
          echo "Verifying contents and permissions of the docs folder..."
          ls -la docs

          echo "Checking file permissions in the docs folder..."
          ls -l docs/release_notes_*.md
          
          # Print the content of the release notes file for verification
          echo "Printing the content of the release notes file..."
          cat docs/release_notes_*.md

      # Step 4: Ensure correct permissions for the docs folder and files
      - name: Set permissions for docs folder
        run: chmod -R 755 docs

      # Step 5: Publish Markdown to Confluence
      - name: Publish Markdown to Confluence
        uses: markdown-confluence/publish-action@v5
        with:
          confluenceBaseUrl: 'https://stadion.atlassian.net/'
          confluenceParentId: 2739208609
          atlassianUserName: 'john@stadion.io'
          atlassianApiToken: ${{ secrets.ATLASSIAN_API_TOKEN }}
          folderToPublish: 'docs' 
          # configFile: '.markdown-confluence.json'  # If you have a configuration file
