name: Auto Label PR Based on Branch Type

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - develop
      - main

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository to access config file and script
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (necessary for running the script)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install @actions/github

      # Step 4: Run the external JavaScript file
      - name: Run PR labeling script
        run: node ./workflow-scripts/labeler.workflow.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
