name: Tag Notification and Comment

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  tag-notification:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # Ensure the token can write comments on PRs
      contents: read  # Ensure the token can read repository content

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Retrieve Tags for PR
        id: get-tags
        run: |
          # Fetch all tags and print them
          git fetch --tags
          TAGS=$(git tag --contains ${{ github.sha }})
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Comment on PR with Tags
        run: |
          TAGS="${{ env.TAGS }}"
          if [ -n "$TAGS" ]; then
            gh pr comment ${{ github.event.pull_request.number }} \
              -b ":label: **Tags Added to PR:**\n\nThe following tags have been added to this PR:\n\n$TAGS"
          else
            echo "No tags found for this PR."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
