name: Prevent PRs that are not release/hotfix to Main branch

on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR branch names
        run: |
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          SOURCE_BRANCH="${{ github.head_ref }}"
          
          if [ "$BASE_BRANCH" == "main" ]; then
            if [[ ! "$SOURCE_BRANCH" =~ ^(hotfix/|release/) ]]; then
              # This will add an annotation in the "Checks" tab
              echo "::error::The source branch ($SOURCE_BRANCH) does not follow the naming conventions. Only branches that start with 'hotfix/' or 'release/' are allowed to merge into 'main'."
              
              # Add a more visible PR comment for clarity
              gh pr comment ${{ github.event.pull_request.number }} \
                -b "⚠️ This PR cannot be merged into the \`main\` branch. Only branches that start with \`hotfix/\` or \`release/\` are allowed. Please update the source branch name or target a different branch."
              
              # Close the PR for violating the rules
              gh pr close ${{ github.event.pull_request.number }}
              
              echo "PR closed due to naming convention issue."
              exit 1  # Fail the job to ensure the action fails
            else
              echo "The PR source branch follows the naming conventions."
            fi
          else
            echo "Base branch is not \`main\`, no action needed."
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
