name: Prevent PRs that are not valid to the Target branch

on:
  pull_request:
    branches:
      - main
      - develop
      - release
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    name: Validate PR Branches
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Validate PR source branch against config
      - name: Run Branch Validator
        run: node ./workflow-scripts/branch-validator.workflow.mjs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
