name: Create Release
on:
  push:
    branches:
      - main

permissions:
  contents: write  
  issues: read    
  deployments: write 

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      # This step checks out the repository to ensure that the workflow has access to the code and tags.
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Get latest tag or create initial tag
      # This step fetches the latest tag from the repository. If no tags are found,
      # it creates and pushes the initial tag (1.0.0) and sets the initial_version flag.
      - name: Get latest tag or create initial tag
        id: get_or_create_tag
        run: |
          echo "Fetching latest tag..."
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "")
          
          if [[ -z "$latest_tag" ]]; then
            echo "No tags found. Setting initial version to 1.0.0"
            latest_tag="1.0.0"
            git tag $latest_tag
            git push origin $latest_tag
            echo "Initial tag created."
            echo "initial_version=true" >> $GITHUB_ENV
          else
            echo "Initial version flag not set."
            echo "initial_version=false" >> $GITHUB_ENV
          fi

          echo "Latest tag is: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      # Step 3: Determine branch type and increment version
      # This step extracts the branch name from the commit message to determine the branch type
      # (release or hotfix). It also increments the version based on the branch type:
      # - For release branches, it increments the minor version and resets the patch to 0.
      # - For hotfix branches, it increments the patch version.
      - name: Determine branch type and increment version
        id: increment_version
        run: |
          echo "Extracting branch name from commit message..."
          branch_name=$(jq -r .head_commit.message < "$GITHUB_EVENT_PATH" | grep -oP 'Merge pull request #[0-9]+ from \K\S+')
          branch_name=${branch_name#*/}
          echo "Branch name extracted: $branch_name"

          if [[ "$branch_name" == release/* ]]; then
            branch_type="release"
            config_file="release-drafter-minor.yml"
          elif [[ "$branch_name" == hotfix/* ]]; then
            branch_type="hotfix"
            config_file="release-drafter-patch.yml"
          else
            echo "Branch does not match expected patterns"
            exit 1
          fi
          
          echo "Branch type determined: $branch_type"
          echo "config_file=$config_file" >> $GITHUB_ENV

          # Increment version based on branch type
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag }}"
          if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
            echo "Error: latest_tag is not in the expected format."
            exit 1
          fi

          if [[ "$branch_type" == "release" ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "$branch_type" == "hotfix" ]]; then
            patch=$((patch + 1))
          else
            echo "Unknown branch type"
            exit 1
          fi
          new_tag="$major.$minor.$patch"
          echo "New tag calculated: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      # Step 4: Draft release notes
      # This step uses Release Drafter to draft release notes based on the branch type and 
      # the selected configuration file for organizing changes in the release.
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ env.config_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Publish the release
      # This step publishes the release by updating the existing draft with the new tag name,
      # ensuring the release is marked as not a draft.
      - name: Publish Release
        run: |
          echo "Publishing new release ${{ env.new_tag }}..."
          gh release edit _DRAFT_ --tag ${{ env.new_tag }} --title "Release v${{ env.new_tag }}" --draft=false 
          echo "Release published: ${{ env.new_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Rebase develop with main for hotfixes
      # If the branch type is hotfix, this step rebases the develop branch with changes 
      # from the main branch to incorporate the latest updates.
      - name: Rebase develop with main for hotfixes
        if: env.branch_type == 'hotfix'
        run: |
          echo "Rebasing develop with main..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin develop
          git checkout develop
          git rebase origin/main
          git push origin develop --force-with-lease
