name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  
  issues: read    
  deployments: write 

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Get latest tag or create initial tag
      - name: Get latest tag or create initial tag
        id: get_or_create_tag
        run: node ./workflow-scripts/get-or-create-tag.workflow.mjs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Determine branch type and select configuration file
      - name: Determine branch type and config
        id: get_branch_info
        run: node ./workflow-scripts/determine-branch-type.workflow.mjs
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}

      # Step 4: Increment version based on branch type
      - name: Increment version
        id: increment_version
        if: env.latest_tag != '' && env.initial_version == 'false'
        run: node ./workflow-scripts/increment-version.workflow.mjs
        env:
          latest_tag: ${{ env.latest_tag }}
          branch_type: ${{ env.branch_type }}

      # Step 5: Draft release notes
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ env.config_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 6: Publish the release
      - name: Publish Release
        id: publish_release
        run: node ./workflow-scripts/publish-release.workflow.mjs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          new_tag: ${{ env.new_tag }}

      # Step 7: Rebase develop with main for hotfixes
      - name: Rebase develop with main for hotfixes
        if: env.branch_type == 'hotfix'
        run: |
          echo "Rebasing develop with main..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin develop
          git checkout develop
          git rebase origin/main
          git push origin develop --force-with-lease
