# .github/workflows/release.yml

name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Needed to create and update releases
  issues: read     # Needed if Release Drafter uses issues
  deployments: write  # If your workflow needs deployment permissions

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest version
        id: get_latest_version
        run: |
          echo "Fetching latest tag..."
          latest_tag=$(gh release list --limit 1 --json tagName --jq '.[0].tagName' || echo "1.0.0")
          echo "Latest tag is: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch type
        id: get_branch_type
        run: |
          echo "Extracting branch name from commit message..."
          branch_name=$(jq -r .head_commit.message < "$GITHUB_EVENT_PATH" | grep -oP 'Merge pull request #[0-9]+ from \K\S+')
          branch_name=$(echo "$branch_name" | sed 's/^[^/]*\///')
          echo "Branch name extracted: $branch_name"
          if [[ "$branch_name" == release/* ]]; then
            branch_type="release"
            config_file="release-drafter-minor.yml"
          elif [[ "$branch_name" == hotfix/* ]]; then
            branch_type="hotfix"
            config_file="release-drafter-patch.yml"
          else
            echo "Branch does not match expected patterns"
            exit 1
          fi
          echo "Branch type determined: $branch_type"
          echo "branch_type=$branch_type" >> $GITHUB_ENV
          echo "config_file=$config_file" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          echo "Incrementing version based on branch type..."
          IFS='.' read -r major minor patch <<< "${{ env.latest_tag }}"
          echo "Current version: $major.$minor.$patch"
          if [[ "${{ env.latest_tag }}" == "" ]]; then
            # If no tags exist yet, start with version 1.0.0
            major=1
            minor=0
            patch=0
          elif [[ "${{ env.branch_type }}" == "release" ]]; then
            minor=$((minor + 1))
            patch=0
          elif [[ "${{ env.branch_type }}" == "hotfix" ]]; then
            patch=$((patch + 1))
          else
            echo "Unknown branch type"
            exit 1
          fi
          new_tag="$major.$minor.$patch"
          echo "New tag calculated: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_ENV

      - name: Draft Release Notes (Minor or Patch)
        uses: release-drafter/release-drafter@v5
        with:
          config-name: ${{ env.config_file }}  # Use correct drafter file based on branch type
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Wait for Release Notes to be Drafted
        run: sleep 10 # Adjust if needed to ensure notes are drafted

      - name: List All Releases
        run: |
          gh release list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check and Update Release Draft
        run: |
          echo "Checking if release draft exists for tag ${{ env.new_tag }}..."
          release_id=$(gh release view ${{ env.new_tag }} --json id --jq '.id' || echo "not found")
          echo "Release ID: $release_id"
          
          if [ "$release_id" = "not found" ]; then
            echo "No release draft found with tag ${{ env.new_tag }}"
            exit 1
          fi
      
          echo "Updating release draft with notes..."
          notes=$(gh release view ${{ env.new_tag }} --json body --jq '.body' || echo "No notes found")
          echo "Notes: $notes"
          
          gh release edit ${{ env.new_tag }} --notes "$notes" --title "Release ${{ env.new_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        id: publish_release
        run: |
          gh release edit ${{ env.new_tag }} --draft=false
          echo "Release published: ${{ env.new_tag }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Release
      #   run: |
      #     echo "Creating release..."
      #     notes=$(gh release view ${{ env.new_tag }} --json body --jq '.body' 2>/dev/null || echo "No notes found")
      #     gh release create ${{ env.new_tag }} --title "Release ${{ env.new_tag }}" --target main --notes "$notes"
      #     echo "Release created: ${{ env.new_tag }}"
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Rebase develop with main for hotfixes
        if: env.branch_type == 'hotfix'
        run: |
          echo "Rebasing develop with main..."
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin develop
          git checkout develop
          git rebase origin/main
          git push origin develop --force-with-lease
          echo "Rebase complete and pushed"